# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(default='21012000', max_length=50),
            preserve_default=False,
        ),
    ]
