# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='student', max_length=50),
            preserve_default=False,
        ),
    ]
