# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Student', max_length=50),
            preserve_default=False,
        ),
    ]
