# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='info',
            field=models.CharField(default='hello!', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='websiteURL',
            field=models.CharField(default='aaaa.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='info',
            field=models.CharField(default='this is the information', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='websiteURL',
            field=models.CharField(default='aaaa.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='info',
            field=models.CharField(default='this is the information', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='websiteURL',
            field=models.CharField(default='aaa.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='info',
            field=models.CharField(default='this is the information', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='websiteURL',
            field=models.CharField(default='aaa.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoo',
            name='info',
            field=models.CharField(default='this is the information', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoo',
            name='websiteURL',
            field=models.CharField(default='aaa.com', max_length=100),
            preserve_default=False,
        ),
    ]
