# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20171027_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='info',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='museum',
            name='info',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='park',
            name='info',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='info',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='info',
            field=models.CharField(max_length=1000),
        ),
    ]
