# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='park',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='park',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='zoo',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='zoo',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='park',
            name='a',
        ),
        migrations.AddField(
            model_name='industry',
            name='industryType',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='departments',
            field=models.TextField(),
        ),
    ]
